# Generated by Django 4.1.5 on 2023-01-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField()),
                ("technology", models.CharField(blank=True, max_length=200, null=True)),
                ("created_add", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
